### ISSUE TITLE
AttractionStatus: Down

### ISSUE THREAD

**Issue by jeanmatthieud** [cubehouse/wdwJS#14]
The DisneyAPI should be able to report "down" attraction status, by another boolean field or by replacing "status" by an integer (-1 (down) / 0 (closed) / 1 (operating)).

In DisneyBase.js, line 85:
```js
obj.active = (ride.waitTime && ride.waitTime.status == "Operating") ? true : false;
```
In fact, "ride.waitTime.status" can be one of: 
```js
["Operating", "Closed", "Down"]
```

**Comment by cubehouse** [comment]
I've been using the generic "active" because we can then support a wider variety of parks that may not have a very good API to give specific information.

I'm not a fan of using integers for states, mainly because it's nicer if the API is self-documenting so it can be understood just by reading the output. I've used them before for things and ended up with things like -7 meaning some special state that got very messy!!

Options as I see them:
* Return a new string "status", modeled on the Disney API results, so all park APIs return either ["Operating", "Closed", "Down"]
* Add two a new booleans under an object "status.broken" and "status.closed", adding some way for parks to declare if they support these new booleans

I think I'm more inclined to return a string. I'm going to look into getting refurbishment data from some of the APIs and ponder while I poke about.

**Comment by cubehouse** [comment]
Started adding new "status" string to some park APIs.

Will add to PR #15 later today.

Most the work is forcing non-Disney parks to return either "Operating", "Closed" or "Down" to ensure we get API consistency. Will push commits later once they're passing all the tests.

**Comment by cubehouse** [comment]
New status string added in 3.0.6. Results will always be "Operating", "Closed" or "Down"

**Comment by jeanmatthieud** [comment]
Thank you !
