### ISSUE TITLE
Universal cooldown period?

### ISSUE THREAD

**Issue by TheConsciousness** [cubehouse/wdwJS#40]
Sometimes when querying the rides for Universal Studios, I notice that I won't receive any ride data. Is there a cooldown period on their API that only allows you to query rides every x amount of minutes?

**Comment by cubehouse** [comment]
I imagine there may be. How often are you calling the API? I would only access it at most once every 4-5 minutes.

**Comment by TheConsciousness** [comment]
I've converted your code to PHP, so it could be subtle differences. I have it set to only be called once every 10 minutes, but there are times when I won't receive any ride data back for at least a half hour. Could an expired token return a success reply, but not attach ride data?

**Comment by cubehouse** [comment]
Hi,

Sorry for the delay. I cannot speak for the stability of park's APIs. We don't have any official support with them for how their API works, we just figure out what we can.

There could be lots of reasons why it would return no data, but still say it's successful. It could be that they are purposefully doing this during busy times, there is a server failure on their side, or they're rate-limiting connections if they see lots of requests.

I would make sure you are setting valid headers, so you are making requests as if a mobile device. Consider running your application through Tor as well to avoid any IP blacklisting. Keeping the requests to once every 10 minutes is also excellent, and good practice to continue with.

I recommend just falling back to the last successfully received ride time if it doesn't return anything.

Since you're using a custom PHP implementation, I'm afraid I can't really assist you any further beyond these pointers. So, I'm going to close this ticket, but please feel free to leave any additional comments if you make any discoveries or find a good solutions to this problem that can benefit others.

**Comment by cubehouse** [comment]
Hi again,

Was just playing with the official app a little and found that the actual Android app does this all the time! Universal seem to return just "null" if you request ride data more than 3-4 times in 10 minutes or so (don't know actual numbers).
This looks to be done by IP, so if you pump through tor and change IP occasionally this may help you.

**Comment by TheConsciousness** [comment]
Great to here! Thank you very much for your testing and your work!
